/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QuantasPlacasSolaresPrecisoRouteImport } from './routes/quantas-placas-solares-preciso'
import { Route as EnergiaSolarRouteImport } from './routes/energia-solar'
import { Route as EconomiaEnergiaSolarRouteImport } from './routes/economia-energia-solar'
import { Route as ConversoresRouteImport } from './routes/conversores'
import { Route as ConversorM2ParaHectareRouteImport } from './routes/conversor-m2-para-hectare'
import { Route as ConversorLitrosParaM3RouteImport } from './routes/conversor-litros-para-m3'
import { Route as ConversorCmParaPolegadaRouteImport } from './routes/conversor-cm-para-polegada'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConstrucaoCivilRouteImport } from './routes/construcao-civil'
import { Route as CalculadoraDeTintaRouteImport } from './routes/calculadora-de-tinta'
import { Route as CalculadoraDeTijolosRouteImport } from './routes/calculadora-de-tijolos'
import { Route as CalculadoraDePisoRouteImport } from './routes/calculadora-de-piso'
import { Route as CalculadoraDeConcretoRouteImport } from './routes/calculadora-de-concreto'
import { Route as CalculadoraDeArgamassaRouteImport } from './routes/calculadora-de-argamassa'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantasPlacasSolaresPrecisoRoute =
  QuantasPlacasSolaresPrecisoRouteImport.update({
    id: '/quantas-placas-solares-preciso',
    path: '/quantas-placas-solares-preciso',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnergiaSolarRoute = EnergiaSolarRouteImport.update({
  id: '/energia-solar',
  path: '/energia-solar',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomiaEnergiaSolarRoute = EconomiaEnergiaSolarRouteImport.update({
  id: '/economia-energia-solar',
  path: '/economia-energia-solar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversoresRoute = ConversoresRouteImport.update({
  id: '/conversores',
  path: '/conversores',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversorM2ParaHectareRoute = ConversorM2ParaHectareRouteImport.update({
  id: '/conversor-m2-para-hectare',
  path: '/conversor-m2-para-hectare',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversorLitrosParaM3Route = ConversorLitrosParaM3RouteImport.update({
  id: '/conversor-litros-para-m3',
  path: '/conversor-litros-para-m3',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversorCmParaPolegadaRoute = ConversorCmParaPolegadaRouteImport.update({
  id: '/conversor-cm-para-polegada',
  path: '/conversor-cm-para-polegada',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstrucaoCivilRoute = ConstrucaoCivilRouteImport.update({
  id: '/construcao-civil',
  path: '/construcao-civil',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraDeTintaRoute = CalculadoraDeTintaRouteImport.update({
  id: '/calculadora-de-tinta',
  path: '/calculadora-de-tinta',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraDeTijolosRoute = CalculadoraDeTijolosRouteImport.update({
  id: '/calculadora-de-tijolos',
  path: '/calculadora-de-tijolos',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraDePisoRoute = CalculadoraDePisoRouteImport.update({
  id: '/calculadora-de-piso',
  path: '/calculadora-de-piso',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraDeConcretoRoute = CalculadoraDeConcretoRouteImport.update({
  id: '/calculadora-de-concreto',
  path: '/calculadora-de-concreto',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraDeArgamassaRoute = CalculadoraDeArgamassaRouteImport.update({
  id: '/calculadora-de-argamassa',
  path: '/calculadora-de-argamassa',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculadora-de-argamassa': typeof CalculadoraDeArgamassaRoute
  '/calculadora-de-concreto': typeof CalculadoraDeConcretoRoute
  '/calculadora-de-piso': typeof CalculadoraDePisoRoute
  '/calculadora-de-tijolos': typeof CalculadoraDeTijolosRoute
  '/calculadora-de-tinta': typeof CalculadoraDeTintaRoute
  '/construcao-civil': typeof ConstrucaoCivilRoute
  '/contato': typeof ContatoRoute
  '/conversor-cm-para-polegada': typeof ConversorCmParaPolegadaRoute
  '/conversor-litros-para-m3': typeof ConversorLitrosParaM3Route
  '/conversor-m2-para-hectare': typeof ConversorM2ParaHectareRoute
  '/conversores': typeof ConversoresRoute
  '/economia-energia-solar': typeof EconomiaEnergiaSolarRoute
  '/energia-solar': typeof EnergiaSolarRoute
  '/quantas-placas-solares-preciso': typeof QuantasPlacasSolaresPrecisoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculadora-de-argamassa': typeof CalculadoraDeArgamassaRoute
  '/calculadora-de-concreto': typeof CalculadoraDeConcretoRoute
  '/calculadora-de-piso': typeof CalculadoraDePisoRoute
  '/calculadora-de-tijolos': typeof CalculadoraDeTijolosRoute
  '/calculadora-de-tinta': typeof CalculadoraDeTintaRoute
  '/construcao-civil': typeof ConstrucaoCivilRoute
  '/contato': typeof ContatoRoute
  '/conversor-cm-para-polegada': typeof ConversorCmParaPolegadaRoute
  '/conversor-litros-para-m3': typeof ConversorLitrosParaM3Route
  '/conversor-m2-para-hectare': typeof ConversorM2ParaHectareRoute
  '/conversores': typeof ConversoresRoute
  '/economia-energia-solar': typeof EconomiaEnergiaSolarRoute
  '/energia-solar': typeof EnergiaSolarRoute
  '/quantas-placas-solares-preciso': typeof QuantasPlacasSolaresPrecisoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculadora-de-argamassa': typeof CalculadoraDeArgamassaRoute
  '/calculadora-de-concreto': typeof CalculadoraDeConcretoRoute
  '/calculadora-de-piso': typeof CalculadoraDePisoRoute
  '/calculadora-de-tijolos': typeof CalculadoraDeTijolosRoute
  '/calculadora-de-tinta': typeof CalculadoraDeTintaRoute
  '/construcao-civil': typeof ConstrucaoCivilRoute
  '/contato': typeof ContatoRoute
  '/conversor-cm-para-polegada': typeof ConversorCmParaPolegadaRoute
  '/conversor-litros-para-m3': typeof ConversorLitrosParaM3Route
  '/conversor-m2-para-hectare': typeof ConversorM2ParaHectareRoute
  '/conversores': typeof ConversoresRoute
  '/economia-energia-solar': typeof EconomiaEnergiaSolarRoute
  '/energia-solar': typeof EnergiaSolarRoute
  '/quantas-placas-solares-preciso': typeof QuantasPlacasSolaresPrecisoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/calculadora-de-argamassa'
    | '/calculadora-de-concreto'
    | '/calculadora-de-piso'
    | '/calculadora-de-tijolos'
    | '/calculadora-de-tinta'
    | '/construcao-civil'
    | '/contato'
    | '/conversor-cm-para-polegada'
    | '/conversor-litros-para-m3'
    | '/conversor-m2-para-hectare'
    | '/conversores'
    | '/economia-energia-solar'
    | '/energia-solar'
    | '/quantas-placas-solares-preciso'
    | '/sitemap.xml'
    | '/sobre'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/calculadora-de-argamassa'
    | '/calculadora-de-concreto'
    | '/calculadora-de-piso'
    | '/calculadora-de-tijolos'
    | '/calculadora-de-tinta'
    | '/construcao-civil'
    | '/contato'
    | '/conversor-cm-para-polegada'
    | '/conversor-litros-para-m3'
    | '/conversor-m2-para-hectare'
    | '/conversores'
    | '/economia-energia-solar'
    | '/energia-solar'
    | '/quantas-placas-solares-preciso'
    | '/sitemap.xml'
    | '/sobre'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/calculadora-de-argamassa'
    | '/calculadora-de-concreto'
    | '/calculadora-de-piso'
    | '/calculadora-de-tijolos'
    | '/calculadora-de-tinta'
    | '/construcao-civil'
    | '/contato'
    | '/conversor-cm-para-polegada'
    | '/conversor-litros-para-m3'
    | '/conversor-m2-para-hectare'
    | '/conversores'
    | '/economia-energia-solar'
    | '/energia-solar'
    | '/quantas-placas-solares-preciso'
    | '/sitemap.xml'
    | '/sobre'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  CalculadoraDeArgamassaRoute: typeof CalculadoraDeArgamassaRoute
  CalculadoraDeConcretoRoute: typeof CalculadoraDeConcretoRoute
  CalculadoraDePisoRoute: typeof CalculadoraDePisoRoute
  CalculadoraDeTijolosRoute: typeof CalculadoraDeTijolosRoute
  CalculadoraDeTintaRoute: typeof CalculadoraDeTintaRoute
  ConstrucaoCivilRoute: typeof ConstrucaoCivilRoute
  ContatoRoute: typeof ContatoRoute
  ConversorCmParaPolegadaRoute: typeof ConversorCmParaPolegadaRoute
  ConversorLitrosParaM3Route: typeof ConversorLitrosParaM3Route
  ConversorM2ParaHectareRoute: typeof ConversorM2ParaHectareRoute
  ConversoresRoute: typeof ConversoresRoute
  EconomiaEnergiaSolarRoute: typeof EconomiaEnergiaSolarRoute
  EnergiaSolarRoute: typeof EnergiaSolarRoute
  QuantasPlacasSolaresPrecisoRoute: typeof QuantasPlacasSolaresPrecisoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quantas-placas-solares-preciso': {
      id: '/quantas-placas-solares-preciso'
      path: '/quantas-placas-solares-preciso'
      fullPath: '/quantas-placas-solares-preciso'
      preLoaderRoute: typeof QuantasPlacasSolaresPrecisoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia-solar': {
      id: '/energia-solar'
      path: '/energia-solar'
      fullPath: '/energia-solar'
      preLoaderRoute: typeof EnergiaSolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economia-energia-solar': {
      id: '/economia-energia-solar'
      path: '/economia-energia-solar'
      fullPath: '/economia-energia-solar'
      preLoaderRoute: typeof EconomiaEnergiaSolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversores': {
      id: '/conversores'
      path: '/conversores'
      fullPath: '/conversores'
      preLoaderRoute: typeof ConversoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversor-m2-para-hectare': {
      id: '/conversor-m2-para-hectare'
      path: '/conversor-m2-para-hectare'
      fullPath: '/conversor-m2-para-hectare'
      preLoaderRoute: typeof ConversorM2ParaHectareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversor-litros-para-m3': {
      id: '/conversor-litros-para-m3'
      path: '/conversor-litros-para-m3'
      fullPath: '/conversor-litros-para-m3'
      preLoaderRoute: typeof ConversorLitrosParaM3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversor-cm-para-polegada': {
      id: '/conversor-cm-para-polegada'
      path: '/conversor-cm-para-polegada'
      fullPath: '/conversor-cm-para-polegada'
      preLoaderRoute: typeof ConversorCmParaPolegadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construcao-civil': {
      id: '/construcao-civil'
      path: '/construcao-civil'
      fullPath: '/construcao-civil'
      preLoaderRoute: typeof ConstrucaoCivilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-de-tinta': {
      id: '/calculadora-de-tinta'
      path: '/calculadora-de-tinta'
      fullPath: '/calculadora-de-tinta'
      preLoaderRoute: typeof CalculadoraDeTintaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-de-tijolos': {
      id: '/calculadora-de-tijolos'
      path: '/calculadora-de-tijolos'
      fullPath: '/calculadora-de-tijolos'
      preLoaderRoute: typeof CalculadoraDeTijolosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-de-piso': {
      id: '/calculadora-de-piso'
      path: '/calculadora-de-piso'
      fullPath: '/calculadora-de-piso'
      preLoaderRoute: typeof CalculadoraDePisoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-de-concreto': {
      id: '/calculadora-de-concreto'
      path: '/calculadora-de-concreto'
      fullPath: '/calculadora-de-concreto'
      preLoaderRoute: typeof CalculadoraDeConcretoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-de-argamassa': {
      id: '/calculadora-de-argamassa'
      path: '/calculadora-de-argamassa'
      fullPath: '/calculadora-de-argamassa'
      preLoaderRoute: typeof CalculadoraDeArgamassaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  CalculadoraDeArgamassaRoute: CalculadoraDeArgamassaRoute,
  CalculadoraDeConcretoRoute: CalculadoraDeConcretoRoute,
  CalculadoraDePisoRoute: CalculadoraDePisoRoute,
  CalculadoraDeTijolosRoute: CalculadoraDeTijolosRoute,
  CalculadoraDeTintaRoute: CalculadoraDeTintaRoute,
  ConstrucaoCivilRoute: ConstrucaoCivilRoute,
  ContatoRoute: ContatoRoute,
  ConversorCmParaPolegadaRoute: ConversorCmParaPolegadaRoute,
  ConversorLitrosParaM3Route: ConversorLitrosParaM3Route,
  ConversorM2ParaHectareRoute: ConversorM2ParaHectareRoute,
  ConversoresRoute: ConversoresRoute,
  EconomiaEnergiaSolarRoute: EconomiaEnergiaSolarRoute,
  EnergiaSolarRoute: EnergiaSolarRoute,
  QuantasPlacasSolaresPrecisoRoute: QuantasPlacasSolaresPrecisoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
