/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as EnergiaSolarRouteImport } from './routes/energia-solar'
import { Route as ConversoresRouteImport } from './routes/conversores'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConstrucaoCivilRouteImport } from './routes/construcao-civil'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConstrucaoCivilIndexRouteImport } from './routes/construcao-civil.index'
import { Route as ConstrucaoCivilTintaRouteImport } from './routes/construcao-civil.tinta'
import { Route as ConstrucaoCivilTijolosRouteImport } from './routes/construcao-civil.tijolos'
import { Route as ConstrucaoCivilPisoRouteImport } from './routes/construcao-civil.piso'
import { Route as ConstrucaoCivilConcretoRouteImport } from './routes/construcao-civil.concreto'
import { Route as ConstrucaoCivilArgamassaRouteImport } from './routes/construcao-civil.argamassa'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergiaSolarRoute = EnergiaSolarRouteImport.update({
  id: '/energia-solar',
  path: '/energia-solar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversoresRoute = ConversoresRouteImport.update({
  id: '/conversores',
  path: '/conversores',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstrucaoCivilRoute = ConstrucaoCivilRouteImport.update({
  id: '/construcao-civil',
  path: '/construcao-civil',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstrucaoCivilIndexRoute = ConstrucaoCivilIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConstrucaoCivilRoute,
} as any)
const ConstrucaoCivilTintaRoute = ConstrucaoCivilTintaRouteImport.update({
  id: '/tinta',
  path: '/tinta',
  getParentRoute: () => ConstrucaoCivilRoute,
} as any)
const ConstrucaoCivilTijolosRoute = ConstrucaoCivilTijolosRouteImport.update({
  id: '/tijolos',
  path: '/tijolos',
  getParentRoute: () => ConstrucaoCivilRoute,
} as any)
const ConstrucaoCivilPisoRoute = ConstrucaoCivilPisoRouteImport.update({
  id: '/piso',
  path: '/piso',
  getParentRoute: () => ConstrucaoCivilRoute,
} as any)
const ConstrucaoCivilConcretoRoute = ConstrucaoCivilConcretoRouteImport.update({
  id: '/concreto',
  path: '/concreto',
  getParentRoute: () => ConstrucaoCivilRoute,
} as any)
const ConstrucaoCivilArgamassaRoute =
  ConstrucaoCivilArgamassaRouteImport.update({
    id: '/argamassa',
    path: '/argamassa',
    getParentRoute: () => ConstrucaoCivilRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/construcao-civil': typeof ConstrucaoCivilRouteWithChildren
  '/contato': typeof ContatoRoute
  '/conversores': typeof ConversoresRoute
  '/energia-solar': typeof EnergiaSolarRoute
  '/sobre': typeof SobreRoute
  '/construcao-civil/argamassa': typeof ConstrucaoCivilArgamassaRoute
  '/construcao-civil/concreto': typeof ConstrucaoCivilConcretoRoute
  '/construcao-civil/piso': typeof ConstrucaoCivilPisoRoute
  '/construcao-civil/tijolos': typeof ConstrucaoCivilTijolosRoute
  '/construcao-civil/tinta': typeof ConstrucaoCivilTintaRoute
  '/construcao-civil/': typeof ConstrucaoCivilIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/conversores': typeof ConversoresRoute
  '/energia-solar': typeof EnergiaSolarRoute
  '/sobre': typeof SobreRoute
  '/construcao-civil/argamassa': typeof ConstrucaoCivilArgamassaRoute
  '/construcao-civil/concreto': typeof ConstrucaoCivilConcretoRoute
  '/construcao-civil/piso': typeof ConstrucaoCivilPisoRoute
  '/construcao-civil/tijolos': typeof ConstrucaoCivilTijolosRoute
  '/construcao-civil/tinta': typeof ConstrucaoCivilTintaRoute
  '/construcao-civil': typeof ConstrucaoCivilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/construcao-civil': typeof ConstrucaoCivilRouteWithChildren
  '/contato': typeof ContatoRoute
  '/conversores': typeof ConversoresRoute
  '/energia-solar': typeof EnergiaSolarRoute
  '/sobre': typeof SobreRoute
  '/construcao-civil/argamassa': typeof ConstrucaoCivilArgamassaRoute
  '/construcao-civil/concreto': typeof ConstrucaoCivilConcretoRoute
  '/construcao-civil/piso': typeof ConstrucaoCivilPisoRoute
  '/construcao-civil/tijolos': typeof ConstrucaoCivilTijolosRoute
  '/construcao-civil/tinta': typeof ConstrucaoCivilTintaRoute
  '/construcao-civil/': typeof ConstrucaoCivilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/construcao-civil'
    | '/contato'
    | '/conversores'
    | '/energia-solar'
    | '/sobre'
    | '/construcao-civil/argamassa'
    | '/construcao-civil/concreto'
    | '/construcao-civil/piso'
    | '/construcao-civil/tijolos'
    | '/construcao-civil/tinta'
    | '/construcao-civil/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/contato'
    | '/conversores'
    | '/energia-solar'
    | '/sobre'
    | '/construcao-civil/argamassa'
    | '/construcao-civil/concreto'
    | '/construcao-civil/piso'
    | '/construcao-civil/tijolos'
    | '/construcao-civil/tinta'
    | '/construcao-civil'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/construcao-civil'
    | '/contato'
    | '/conversores'
    | '/energia-solar'
    | '/sobre'
    | '/construcao-civil/argamassa'
    | '/construcao-civil/concreto'
    | '/construcao-civil/piso'
    | '/construcao-civil/tijolos'
    | '/construcao-civil/tinta'
    | '/construcao-civil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  ConstrucaoCivilRoute: typeof ConstrucaoCivilRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  ConversoresRoute: typeof ConversoresRoute
  EnergiaSolarRoute: typeof EnergiaSolarRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia-solar': {
      id: '/energia-solar'
      path: '/energia-solar'
      fullPath: '/energia-solar'
      preLoaderRoute: typeof EnergiaSolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversores': {
      id: '/conversores'
      path: '/conversores'
      fullPath: '/conversores'
      preLoaderRoute: typeof ConversoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construcao-civil': {
      id: '/construcao-civil'
      path: '/construcao-civil'
      fullPath: '/construcao-civil'
      preLoaderRoute: typeof ConstrucaoCivilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construcao-civil/': {
      id: '/construcao-civil/'
      path: '/'
      fullPath: '/construcao-civil/'
      preLoaderRoute: typeof ConstrucaoCivilIndexRouteImport
      parentRoute: typeof ConstrucaoCivilRoute
    }
    '/construcao-civil/tinta': {
      id: '/construcao-civil/tinta'
      path: '/tinta'
      fullPath: '/construcao-civil/tinta'
      preLoaderRoute: typeof ConstrucaoCivilTintaRouteImport
      parentRoute: typeof ConstrucaoCivilRoute
    }
    '/construcao-civil/tijolos': {
      id: '/construcao-civil/tijolos'
      path: '/tijolos'
      fullPath: '/construcao-civil/tijolos'
      preLoaderRoute: typeof ConstrucaoCivilTijolosRouteImport
      parentRoute: typeof ConstrucaoCivilRoute
    }
    '/construcao-civil/piso': {
      id: '/construcao-civil/piso'
      path: '/piso'
      fullPath: '/construcao-civil/piso'
      preLoaderRoute: typeof ConstrucaoCivilPisoRouteImport
      parentRoute: typeof ConstrucaoCivilRoute
    }
    '/construcao-civil/concreto': {
      id: '/construcao-civil/concreto'
      path: '/concreto'
      fullPath: '/construcao-civil/concreto'
      preLoaderRoute: typeof ConstrucaoCivilConcretoRouteImport
      parentRoute: typeof ConstrucaoCivilRoute
    }
    '/construcao-civil/argamassa': {
      id: '/construcao-civil/argamassa'
      path: '/argamassa'
      fullPath: '/construcao-civil/argamassa'
      preLoaderRoute: typeof ConstrucaoCivilArgamassaRouteImport
      parentRoute: typeof ConstrucaoCivilRoute
    }
  }
}

interface ConstrucaoCivilRouteChildren {
  ConstrucaoCivilArgamassaRoute: typeof ConstrucaoCivilArgamassaRoute
  ConstrucaoCivilConcretoRoute: typeof ConstrucaoCivilConcretoRoute
  ConstrucaoCivilPisoRoute: typeof ConstrucaoCivilPisoRoute
  ConstrucaoCivilTijolosRoute: typeof ConstrucaoCivilTijolosRoute
  ConstrucaoCivilTintaRoute: typeof ConstrucaoCivilTintaRoute
  ConstrucaoCivilIndexRoute: typeof ConstrucaoCivilIndexRoute
}

const ConstrucaoCivilRouteChildren: ConstrucaoCivilRouteChildren = {
  ConstrucaoCivilArgamassaRoute: ConstrucaoCivilArgamassaRoute,
  ConstrucaoCivilConcretoRoute: ConstrucaoCivilConcretoRoute,
  ConstrucaoCivilPisoRoute: ConstrucaoCivilPisoRoute,
  ConstrucaoCivilTijolosRoute: ConstrucaoCivilTijolosRoute,
  ConstrucaoCivilTintaRoute: ConstrucaoCivilTintaRoute,
  ConstrucaoCivilIndexRoute: ConstrucaoCivilIndexRoute,
}

const ConstrucaoCivilRouteWithChildren = ConstrucaoCivilRoute._addFileChildren(
  ConstrucaoCivilRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  ConstrucaoCivilRoute: ConstrucaoCivilRouteWithChildren,
  ContatoRoute: ContatoRoute,
  ConversoresRoute: ConversoresRoute,
  EnergiaSolarRoute: EnergiaSolarRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
