/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SimuladorSolarAvancadoRouteImport } from './routes/simulador-solar-avancado'
import { Route as QuantasPlacasSolaresPrecisoRouteImport } from './routes/quantas-placas-solares-preciso'
import { Route as PoliticaDmcaRouteImport } from './routes/politica-dmca'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PoliticaDeCookiesRouteImport } from './routes/politica-de-cookies'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as EnergiaSolarRouteImport } from './routes/energia-solar'
import { Route as EconomiaEnergiaSolarRouteImport } from './routes/economia-energia-solar'
import { Route as ConversoresRouteImport } from './routes/conversores'
import { Route as ConversorM2ParaHectareRouteImport } from './routes/conversor-m2-para-hectare'
import { Route as ConversorLitrosParaM3RouteImport } from './routes/conversor-litros-para-m3'
import { Route as ConversorCmParaPolegadaRouteImport } from './routes/conversor-cm-para-polegada'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConstrucaoCivilRouteImport } from './routes/construcao-civil'
import { Route as CalculadoraRejunteRouteImport } from './routes/calculadora-rejunte'
import { Route as CalculadoraDeTubosRouteImport } from './routes/calculadora-de-tubos'
import { Route as CalculadoraDeTintaRouteImport } from './routes/calculadora-de-tinta'
import { Route as CalculadoraDeTijolosRouteImport } from './routes/calculadora-de-tijolos'
import { Route as CalculadoraDeTelhasRouteImport } from './routes/calculadora-de-telhas'
import { Route as CalculadoraDeRebocoRouteImport } from './routes/calculadora-de-reboco'
import { Route as CalculadoraDePisoRouteImport } from './routes/calculadora-de-piso'
import { Route as CalculadoraDeFormaRouteImport } from './routes/calculadora-de-forma'
import { Route as CalculadoraDeEsquadriasRouteImport } from './routes/calculadora-de-esquadrias'
import { Route as CalculadoraDeConcretoRouteImport } from './routes/calculadora-de-concreto'
import { Route as CalculadoraDeCimentoRouteImport } from './routes/calculadora-de-cimento'
import { Route as CalculadoraDeBritaRouteImport } from './routes/calculadora-de-brita'
import { Route as CalculadoraDeBlocosRouteImport } from './routes/calculadora-de-blocos'
import { Route as CalculadoraDeArgamassaRouteImport } from './routes/calculadora-de-argamassa'
import { Route as CalculadoraDeAreiaRouteImport } from './routes/calculadora-de-areia'
import { Route as CalculadoraDeAcoRouteImport } from './routes/calculadora-de-aco'
import { Route as CalculadoraArCondicionadoRouteImport } from './routes/calculadora-ar-condicionado'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnergiaSolarIndexRouteImport } from './routes/energia-solar.index'
import { Route as ConstrucaoCivilIndexRouteImport } from './routes/construcao-civil.index'
import { Route as FerramentasOrcamentoDomesticoRouteImport } from './routes/ferramentas.orcamento-domestico'
import { Route as EnergiaSolarSimulacaoRadiacaoRouteImport } from './routes/energia-solar.simulacao-radiacao'
import { Route as EnergiaSolarIncentivosSubsidiosRegionaisRouteImport } from './routes/energia-solar.incentivos-subsidios-regionais'
import { Route as EnergiaSolarEstimadorCustoTotalRouteImport } from './routes/energia-solar.estimador-custo-total'
import { Route as EnergiaSolarConversorKwKwhRouteImport } from './routes/energia-solar.conversor-kw-kwh'
import { Route as EnergiaSolarComparadorSistemasRouteImport } from './routes/energia-solar.comparador-sistemas'
import { Route as EnergiaSolarCalculadoraPerdasEficienciaRouteImport } from './routes/energia-solar.calculadora-perdas-eficiencia'
import { Route as EnergiaSolarCalculadoraPaybackRouteImport } from './routes/energia-solar.calculadora-payback'
import { Route as EnergiaSolarCalculadoraInversorRouteImport } from './routes/energia-solar.calculadora-inversor'
import { Route as EnergiaSolarCalculadoraBateriaRouteImport } from './routes/energia-solar.calculadora-bateria'
import { Route as EnergiaSolarCalculadoraAreaLayoutPaineisRouteImport } from './routes/energia-solar.calculadora-area-layout-paineis'
import { Route as ConstrucaoCivilSimuladorIluminacaoFachadasRouteImport } from './routes/construcao-civil.simulador-iluminacao-fachadas'
import { Route as ConstrucaoCivilQuantificacaoTelhasPecasRouteImport } from './routes/construcao-civil.quantificacao-telhas-pecas'
import { Route as ConstrucaoCivilPerdaAtritoTubulacoesRouteImport } from './routes/construcao-civil.perda-atrito-tubulacoes'
import { Route as ConstrucaoCivilOrcamentoPorEtapaRouteImport } from './routes/construcao-civil.orcamento-por-etapa'
import { Route as ConstrucaoCivilHvacPerdasRouteImport } from './routes/construcao-civil.hvac-perdas'
import { Route as ConstrucaoCivilFundacaoSapataRouteImport } from './routes/construcao-civil.fundacao-sapata'
import { Route as ConstrucaoCivilEstruturasMetalicasBasicasRouteImport } from './routes/construcao-civil.estruturas-metalicas-basicas'
import { Route as ConstrucaoCivilDrenagemCalhasRouteImport } from './routes/construcao-civil.drenagem-calhas'
import { Route as ConstrucaoCivilDimensionamentoEletricoRouteImport } from './routes/construcao-civil.dimensionamento-eletrico'
import { Route as ConstrucaoCivilConversorUnidadesTecnicasRouteImport } from './routes/construcao-civil.conversor-unidades-tecnicas'
import { Route as ConstrucaoCivilCalculadoraMaoObraRouteImport } from './routes/construcao-civil.calculadora-mao-obra'
import { Route as ConstrucaoCivilCalculadoraLajesRouteImport } from './routes/construcao-civil.calculadora-lajes'
import { Route as ConstrucaoCivilAndaimesEscorasRouteImport } from './routes/construcao-civil.andaimes-escoras'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogCategoriaCategoriaRouteImport } from './routes/blog.categoria.$categoria'

const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladorSolarAvancadoRoute = SimuladorSolarAvancadoRouteImport.update({
  id: '/simulador-solar-avancado',
  path: '/simulador-solar-avancado',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantasPlacasSolaresPrecisoRoute =
  QuantasPlacasSolaresPrecisoRouteImport.update({
    id: '/quantas-placas-solares-preciso',
    path: '/quantas-placas-solares-preciso',
    getParentRoute: () => rootRouteImport,
  } as any)
const PoliticaDmcaRoute = PoliticaDmcaRouteImport.update({
  id: '/politica-dmca',
  path: '/politica-dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeCookiesRoute = PoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergiaSolarRoute = EnergiaSolarRouteImport.update({
  id: '/energia-solar',
  path: '/energia-solar',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomiaEnergiaSolarRoute = EconomiaEnergiaSolarRouteImport.update({
  id: '/economia-energia-solar',
  path: '/economia-energia-solar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversoresRoute = ConversoresRouteImport.update({
  id: '/conversores',
  path: '/conversores',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversorM2ParaHectareRoute = ConversorM2ParaHectareRouteImport.update({
  id: '/conversor-m2-para-hectare',
  path: '/conversor-m2-para-hectare',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversorLitrosParaM3Route = ConversorLitrosParaM3RouteImport.update({
  id: '/conversor-litros-para-m3',
  path: '/conversor-litros-para-m3',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversorCmParaPolegadaRoute = ConversorCmParaPolegadaRouteImport.update({
  id: '/conversor-cm-para-polegada',
  path: '/conversor-cm-para-polegada',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstrucaoCivilRoute = ConstrucaoCivilRouteImport.update({
  id: '/construcao-civil',
  path: '/construcao-civil',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraRejunteRoute = CalculadoraRejunteRouteImport.update({
  id: '/calculadora-rejunte',
  path: '/calculadora-rejunte',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraDeTubosRoute = CalculadoraDeTubosRouteImport.update({
  id: '/calculadora-de-tubos',
  path: '/calculadora-de-tubos',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraDeTintaRoute = CalculadoraDeTintaRouteImport.update({
  id: '/calculadora-de-tinta',
  path: '/calculadora-de-tinta',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraDeTijolosRoute = CalculadoraDeTijolosRouteImport.update({
  id: '/calculadora-de-tijolos',
  path: '/calculadora-de-tijolos',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraDeTelhasRoute = CalculadoraDeTelhasRouteImport.update({
  id: '/calculadora-de-telhas',
  path: '/calculadora-de-telhas',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraDeRebocoRoute = CalculadoraDeRebocoRouteImport.update({
  id: '/calculadora-de-reboco',
  path: '/calculadora-de-reboco',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraDePisoRoute = CalculadoraDePisoRouteImport.update({
  id: '/calculadora-de-piso',
  path: '/calculadora-de-piso',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraDeFormaRoute = CalculadoraDeFormaRouteImport.update({
  id: '/calculadora-de-forma',
  path: '/calculadora-de-forma',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraDeEsquadriasRoute = CalculadoraDeEsquadriasRouteImport.update({
  id: '/calculadora-de-esquadrias',
  path: '/calculadora-de-esquadrias',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraDeConcretoRoute = CalculadoraDeConcretoRouteImport.update({
  id: '/calculadora-de-concreto',
  path: '/calculadora-de-concreto',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraDeCimentoRoute = CalculadoraDeCimentoRouteImport.update({
  id: '/calculadora-de-cimento',
  path: '/calculadora-de-cimento',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraDeBritaRoute = CalculadoraDeBritaRouteImport.update({
  id: '/calculadora-de-brita',
  path: '/calculadora-de-brita',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraDeBlocosRoute = CalculadoraDeBlocosRouteImport.update({
  id: '/calculadora-de-blocos',
  path: '/calculadora-de-blocos',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraDeArgamassaRoute = CalculadoraDeArgamassaRouteImport.update({
  id: '/calculadora-de-argamassa',
  path: '/calculadora-de-argamassa',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraDeAreiaRoute = CalculadoraDeAreiaRouteImport.update({
  id: '/calculadora-de-areia',
  path: '/calculadora-de-areia',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraDeAcoRoute = CalculadoraDeAcoRouteImport.update({
  id: '/calculadora-de-aco',
  path: '/calculadora-de-aco',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraArCondicionadoRoute =
  CalculadoraArCondicionadoRouteImport.update({
    id: '/calculadora-ar-condicionado',
    path: '/calculadora-ar-condicionado',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergiaSolarIndexRoute = EnergiaSolarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnergiaSolarRoute,
} as any)
const ConstrucaoCivilIndexRoute = ConstrucaoCivilIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConstrucaoCivilRoute,
} as any)
const FerramentasOrcamentoDomesticoRoute =
  FerramentasOrcamentoDomesticoRouteImport.update({
    id: '/ferramentas/orcamento-domestico',
    path: '/ferramentas/orcamento-domestico',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnergiaSolarSimulacaoRadiacaoRoute =
  EnergiaSolarSimulacaoRadiacaoRouteImport.update({
    id: '/simulacao-radiacao',
    path: '/simulacao-radiacao',
    getParentRoute: () => EnergiaSolarRoute,
  } as any)
const EnergiaSolarIncentivosSubsidiosRegionaisRoute =
  EnergiaSolarIncentivosSubsidiosRegionaisRouteImport.update({
    id: '/incentivos-subsidios-regionais',
    path: '/incentivos-subsidios-regionais',
    getParentRoute: () => EnergiaSolarRoute,
  } as any)
const EnergiaSolarEstimadorCustoTotalRoute =
  EnergiaSolarEstimadorCustoTotalRouteImport.update({
    id: '/estimador-custo-total',
    path: '/estimador-custo-total',
    getParentRoute: () => EnergiaSolarRoute,
  } as any)
const EnergiaSolarConversorKwKwhRoute =
  EnergiaSolarConversorKwKwhRouteImport.update({
    id: '/conversor-kw-kwh',
    path: '/conversor-kw-kwh',
    getParentRoute: () => EnergiaSolarRoute,
  } as any)
const EnergiaSolarComparadorSistemasRoute =
  EnergiaSolarComparadorSistemasRouteImport.update({
    id: '/comparador-sistemas',
    path: '/comparador-sistemas',
    getParentRoute: () => EnergiaSolarRoute,
  } as any)
const EnergiaSolarCalculadoraPerdasEficienciaRoute =
  EnergiaSolarCalculadoraPerdasEficienciaRouteImport.update({
    id: '/calculadora-perdas-eficiencia',
    path: '/calculadora-perdas-eficiencia',
    getParentRoute: () => EnergiaSolarRoute,
  } as any)
const EnergiaSolarCalculadoraPaybackRoute =
  EnergiaSolarCalculadoraPaybackRouteImport.update({
    id: '/calculadora-payback',
    path: '/calculadora-payback',
    getParentRoute: () => EnergiaSolarRoute,
  } as any)
const EnergiaSolarCalculadoraInversorRoute =
  EnergiaSolarCalculadoraInversorRouteImport.update({
    id: '/calculadora-inversor',
    path: '/calculadora-inversor',
    getParentRoute: () => EnergiaSolarRoute,
  } as any)
const EnergiaSolarCalculadoraBateriaRoute =
  EnergiaSolarCalculadoraBateriaRouteImport.update({
    id: '/calculadora-bateria',
    path: '/calculadora-bateria',
    getParentRoute: () => EnergiaSolarRoute,
  } as any)
const EnergiaSolarCalculadoraAreaLayoutPaineisRoute =
  EnergiaSolarCalculadoraAreaLayoutPaineisRouteImport.update({
    id: '/calculadora-area-layout-paineis',
    path: '/calculadora-area-layout-paineis',
    getParentRoute: () => EnergiaSolarRoute,
  } as any)
const ConstrucaoCivilSimuladorIluminacaoFachadasRoute =
  ConstrucaoCivilSimuladorIluminacaoFachadasRouteImport.update({
    id: '/simulador-iluminacao-fachadas',
    path: '/simulador-iluminacao-fachadas',
    getParentRoute: () => ConstrucaoCivilRoute,
  } as any)
const ConstrucaoCivilQuantificacaoTelhasPecasRoute =
  ConstrucaoCivilQuantificacaoTelhasPecasRouteImport.update({
    id: '/quantificacao-telhas-pecas',
    path: '/quantificacao-telhas-pecas',
    getParentRoute: () => ConstrucaoCivilRoute,
  } as any)
const ConstrucaoCivilPerdaAtritoTubulacoesRoute =
  ConstrucaoCivilPerdaAtritoTubulacoesRouteImport.update({
    id: '/perda-atrito-tubulacoes',
    path: '/perda-atrito-tubulacoes',
    getParentRoute: () => ConstrucaoCivilRoute,
  } as any)
const ConstrucaoCivilOrcamentoPorEtapaRoute =
  ConstrucaoCivilOrcamentoPorEtapaRouteImport.update({
    id: '/orcamento-por-etapa',
    path: '/orcamento-por-etapa',
    getParentRoute: () => ConstrucaoCivilRoute,
  } as any)
const ConstrucaoCivilHvacPerdasRoute =
  ConstrucaoCivilHvacPerdasRouteImport.update({
    id: '/hvac-perdas',
    path: '/hvac-perdas',
    getParentRoute: () => ConstrucaoCivilRoute,
  } as any)
const ConstrucaoCivilFundacaoSapataRoute =
  ConstrucaoCivilFundacaoSapataRouteImport.update({
    id: '/fundacao-sapata',
    path: '/fundacao-sapata',
    getParentRoute: () => ConstrucaoCivilRoute,
  } as any)
const ConstrucaoCivilEstruturasMetalicasBasicasRoute =
  ConstrucaoCivilEstruturasMetalicasBasicasRouteImport.update({
    id: '/estruturas-metalicas-basicas',
    path: '/estruturas-metalicas-basicas',
    getParentRoute: () => ConstrucaoCivilRoute,
  } as any)
const ConstrucaoCivilDrenagemCalhasRoute =
  ConstrucaoCivilDrenagemCalhasRouteImport.update({
    id: '/drenagem-calhas',
    path: '/drenagem-calhas',
    getParentRoute: () => ConstrucaoCivilRoute,
  } as any)
const ConstrucaoCivilDimensionamentoEletricoRoute =
  ConstrucaoCivilDimensionamentoEletricoRouteImport.update({
    id: '/dimensionamento-eletrico',
    path: '/dimensionamento-eletrico',
    getParentRoute: () => ConstrucaoCivilRoute,
  } as any)
const ConstrucaoCivilConversorUnidadesTecnicasRoute =
  ConstrucaoCivilConversorUnidadesTecnicasRouteImport.update({
    id: '/conversor-unidades-tecnicas',
    path: '/conversor-unidades-tecnicas',
    getParentRoute: () => ConstrucaoCivilRoute,
  } as any)
const ConstrucaoCivilCalculadoraMaoObraRoute =
  ConstrucaoCivilCalculadoraMaoObraRouteImport.update({
    id: '/calculadora-mao-obra',
    path: '/calculadora-mao-obra',
    getParentRoute: () => ConstrucaoCivilRoute,
  } as any)
const ConstrucaoCivilCalculadoraLajesRoute =
  ConstrucaoCivilCalculadoraLajesRouteImport.update({
    id: '/calculadora-lajes',
    path: '/calculadora-lajes',
    getParentRoute: () => ConstrucaoCivilRoute,
  } as any)
const ConstrucaoCivilAndaimesEscorasRoute =
  ConstrucaoCivilAndaimesEscorasRouteImport.update({
    id: '/andaimes-escoras',
    path: '/andaimes-escoras',
    getParentRoute: () => ConstrucaoCivilRoute,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BlogCategoriaCategoriaRoute = BlogCategoriaCategoriaRouteImport.update({
  id: '/categoria/$categoria',
  path: '/categoria/$categoria',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculadora-ar-condicionado': typeof CalculadoraArCondicionadoRoute
  '/calculadora-de-aco': typeof CalculadoraDeAcoRoute
  '/calculadora-de-areia': typeof CalculadoraDeAreiaRoute
  '/calculadora-de-argamassa': typeof CalculadoraDeArgamassaRoute
  '/calculadora-de-blocos': typeof CalculadoraDeBlocosRoute
  '/calculadora-de-brita': typeof CalculadoraDeBritaRoute
  '/calculadora-de-cimento': typeof CalculadoraDeCimentoRoute
  '/calculadora-de-concreto': typeof CalculadoraDeConcretoRoute
  '/calculadora-de-esquadrias': typeof CalculadoraDeEsquadriasRoute
  '/calculadora-de-forma': typeof CalculadoraDeFormaRoute
  '/calculadora-de-piso': typeof CalculadoraDePisoRoute
  '/calculadora-de-reboco': typeof CalculadoraDeRebocoRoute
  '/calculadora-de-telhas': typeof CalculadoraDeTelhasRoute
  '/calculadora-de-tijolos': typeof CalculadoraDeTijolosRoute
  '/calculadora-de-tinta': typeof CalculadoraDeTintaRoute
  '/calculadora-de-tubos': typeof CalculadoraDeTubosRoute
  '/calculadora-rejunte': typeof CalculadoraRejunteRoute
  '/construcao-civil': typeof ConstrucaoCivilRouteWithChildren
  '/contato': typeof ContatoRoute
  '/conversor-cm-para-polegada': typeof ConversorCmParaPolegadaRoute
  '/conversor-litros-para-m3': typeof ConversorLitrosParaM3Route
  '/conversor-m2-para-hectare': typeof ConversorM2ParaHectareRoute
  '/conversores': typeof ConversoresRoute
  '/economia-energia-solar': typeof EconomiaEnergiaSolarRoute
  '/energia-solar': typeof EnergiaSolarRouteWithChildren
  '/equipe': typeof EquipeRoute
  '/faq': typeof FaqRoute
  '/metodologia': typeof MetodologiaRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-dmca': typeof PoliticaDmcaRoute
  '/quantas-placas-solares-preciso': typeof QuantasPlacasSolaresPrecisoRoute
  '/simulador-solar-avancado': typeof SimuladorSolarAvancadoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/construcao-civil/andaimes-escoras': typeof ConstrucaoCivilAndaimesEscorasRoute
  '/construcao-civil/calculadora-lajes': typeof ConstrucaoCivilCalculadoraLajesRoute
  '/construcao-civil/calculadora-mao-obra': typeof ConstrucaoCivilCalculadoraMaoObraRoute
  '/construcao-civil/conversor-unidades-tecnicas': typeof ConstrucaoCivilConversorUnidadesTecnicasRoute
  '/construcao-civil/dimensionamento-eletrico': typeof ConstrucaoCivilDimensionamentoEletricoRoute
  '/construcao-civil/drenagem-calhas': typeof ConstrucaoCivilDrenagemCalhasRoute
  '/construcao-civil/estruturas-metalicas-basicas': typeof ConstrucaoCivilEstruturasMetalicasBasicasRoute
  '/construcao-civil/fundacao-sapata': typeof ConstrucaoCivilFundacaoSapataRoute
  '/construcao-civil/hvac-perdas': typeof ConstrucaoCivilHvacPerdasRoute
  '/construcao-civil/orcamento-por-etapa': typeof ConstrucaoCivilOrcamentoPorEtapaRoute
  '/construcao-civil/perda-atrito-tubulacoes': typeof ConstrucaoCivilPerdaAtritoTubulacoesRoute
  '/construcao-civil/quantificacao-telhas-pecas': typeof ConstrucaoCivilQuantificacaoTelhasPecasRoute
  '/construcao-civil/simulador-iluminacao-fachadas': typeof ConstrucaoCivilSimuladorIluminacaoFachadasRoute
  '/energia-solar/calculadora-area-layout-paineis': typeof EnergiaSolarCalculadoraAreaLayoutPaineisRoute
  '/energia-solar/calculadora-bateria': typeof EnergiaSolarCalculadoraBateriaRoute
  '/energia-solar/calculadora-inversor': typeof EnergiaSolarCalculadoraInversorRoute
  '/energia-solar/calculadora-payback': typeof EnergiaSolarCalculadoraPaybackRoute
  '/energia-solar/calculadora-perdas-eficiencia': typeof EnergiaSolarCalculadoraPerdasEficienciaRoute
  '/energia-solar/comparador-sistemas': typeof EnergiaSolarComparadorSistemasRoute
  '/energia-solar/conversor-kw-kwh': typeof EnergiaSolarConversorKwKwhRoute
  '/energia-solar/estimador-custo-total': typeof EnergiaSolarEstimadorCustoTotalRoute
  '/energia-solar/incentivos-subsidios-regionais': typeof EnergiaSolarIncentivosSubsidiosRegionaisRoute
  '/energia-solar/simulacao-radiacao': typeof EnergiaSolarSimulacaoRadiacaoRoute
  '/ferramentas/orcamento-domestico': typeof FerramentasOrcamentoDomesticoRoute
  '/construcao-civil/': typeof ConstrucaoCivilIndexRoute
  '/energia-solar/': typeof EnergiaSolarIndexRoute
  '/blog/categoria/$categoria': typeof BlogCategoriaCategoriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculadora-ar-condicionado': typeof CalculadoraArCondicionadoRoute
  '/calculadora-de-aco': typeof CalculadoraDeAcoRoute
  '/calculadora-de-areia': typeof CalculadoraDeAreiaRoute
  '/calculadora-de-argamassa': typeof CalculadoraDeArgamassaRoute
  '/calculadora-de-blocos': typeof CalculadoraDeBlocosRoute
  '/calculadora-de-brita': typeof CalculadoraDeBritaRoute
  '/calculadora-de-cimento': typeof CalculadoraDeCimentoRoute
  '/calculadora-de-concreto': typeof CalculadoraDeConcretoRoute
  '/calculadora-de-esquadrias': typeof CalculadoraDeEsquadriasRoute
  '/calculadora-de-forma': typeof CalculadoraDeFormaRoute
  '/calculadora-de-piso': typeof CalculadoraDePisoRoute
  '/calculadora-de-reboco': typeof CalculadoraDeRebocoRoute
  '/calculadora-de-telhas': typeof CalculadoraDeTelhasRoute
  '/calculadora-de-tijolos': typeof CalculadoraDeTijolosRoute
  '/calculadora-de-tinta': typeof CalculadoraDeTintaRoute
  '/calculadora-de-tubos': typeof CalculadoraDeTubosRoute
  '/calculadora-rejunte': typeof CalculadoraRejunteRoute
  '/contato': typeof ContatoRoute
  '/conversor-cm-para-polegada': typeof ConversorCmParaPolegadaRoute
  '/conversor-litros-para-m3': typeof ConversorLitrosParaM3Route
  '/conversor-m2-para-hectare': typeof ConversorM2ParaHectareRoute
  '/conversores': typeof ConversoresRoute
  '/economia-energia-solar': typeof EconomiaEnergiaSolarRoute
  '/equipe': typeof EquipeRoute
  '/faq': typeof FaqRoute
  '/metodologia': typeof MetodologiaRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-dmca': typeof PoliticaDmcaRoute
  '/quantas-placas-solares-preciso': typeof QuantasPlacasSolaresPrecisoRoute
  '/simulador-solar-avancado': typeof SimuladorSolarAvancadoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/construcao-civil/andaimes-escoras': typeof ConstrucaoCivilAndaimesEscorasRoute
  '/construcao-civil/calculadora-lajes': typeof ConstrucaoCivilCalculadoraLajesRoute
  '/construcao-civil/calculadora-mao-obra': typeof ConstrucaoCivilCalculadoraMaoObraRoute
  '/construcao-civil/conversor-unidades-tecnicas': typeof ConstrucaoCivilConversorUnidadesTecnicasRoute
  '/construcao-civil/dimensionamento-eletrico': typeof ConstrucaoCivilDimensionamentoEletricoRoute
  '/construcao-civil/drenagem-calhas': typeof ConstrucaoCivilDrenagemCalhasRoute
  '/construcao-civil/estruturas-metalicas-basicas': typeof ConstrucaoCivilEstruturasMetalicasBasicasRoute
  '/construcao-civil/fundacao-sapata': typeof ConstrucaoCivilFundacaoSapataRoute
  '/construcao-civil/hvac-perdas': typeof ConstrucaoCivilHvacPerdasRoute
  '/construcao-civil/orcamento-por-etapa': typeof ConstrucaoCivilOrcamentoPorEtapaRoute
  '/construcao-civil/perda-atrito-tubulacoes': typeof ConstrucaoCivilPerdaAtritoTubulacoesRoute
  '/construcao-civil/quantificacao-telhas-pecas': typeof ConstrucaoCivilQuantificacaoTelhasPecasRoute
  '/construcao-civil/simulador-iluminacao-fachadas': typeof ConstrucaoCivilSimuladorIluminacaoFachadasRoute
  '/energia-solar/calculadora-area-layout-paineis': typeof EnergiaSolarCalculadoraAreaLayoutPaineisRoute
  '/energia-solar/calculadora-bateria': typeof EnergiaSolarCalculadoraBateriaRoute
  '/energia-solar/calculadora-inversor': typeof EnergiaSolarCalculadoraInversorRoute
  '/energia-solar/calculadora-payback': typeof EnergiaSolarCalculadoraPaybackRoute
  '/energia-solar/calculadora-perdas-eficiencia': typeof EnergiaSolarCalculadoraPerdasEficienciaRoute
  '/energia-solar/comparador-sistemas': typeof EnergiaSolarComparadorSistemasRoute
  '/energia-solar/conversor-kw-kwh': typeof EnergiaSolarConversorKwKwhRoute
  '/energia-solar/estimador-custo-total': typeof EnergiaSolarEstimadorCustoTotalRoute
  '/energia-solar/incentivos-subsidios-regionais': typeof EnergiaSolarIncentivosSubsidiosRegionaisRoute
  '/energia-solar/simulacao-radiacao': typeof EnergiaSolarSimulacaoRadiacaoRoute
  '/ferramentas/orcamento-domestico': typeof FerramentasOrcamentoDomesticoRoute
  '/construcao-civil': typeof ConstrucaoCivilIndexRoute
  '/energia-solar': typeof EnergiaSolarIndexRoute
  '/blog/categoria/$categoria': typeof BlogCategoriaCategoriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculadora-ar-condicionado': typeof CalculadoraArCondicionadoRoute
  '/calculadora-de-aco': typeof CalculadoraDeAcoRoute
  '/calculadora-de-areia': typeof CalculadoraDeAreiaRoute
  '/calculadora-de-argamassa': typeof CalculadoraDeArgamassaRoute
  '/calculadora-de-blocos': typeof CalculadoraDeBlocosRoute
  '/calculadora-de-brita': typeof CalculadoraDeBritaRoute
  '/calculadora-de-cimento': typeof CalculadoraDeCimentoRoute
  '/calculadora-de-concreto': typeof CalculadoraDeConcretoRoute
  '/calculadora-de-esquadrias': typeof CalculadoraDeEsquadriasRoute
  '/calculadora-de-forma': typeof CalculadoraDeFormaRoute
  '/calculadora-de-piso': typeof CalculadoraDePisoRoute
  '/calculadora-de-reboco': typeof CalculadoraDeRebocoRoute
  '/calculadora-de-telhas': typeof CalculadoraDeTelhasRoute
  '/calculadora-de-tijolos': typeof CalculadoraDeTijolosRoute
  '/calculadora-de-tinta': typeof CalculadoraDeTintaRoute
  '/calculadora-de-tubos': typeof CalculadoraDeTubosRoute
  '/calculadora-rejunte': typeof CalculadoraRejunteRoute
  '/construcao-civil': typeof ConstrucaoCivilRouteWithChildren
  '/contato': typeof ContatoRoute
  '/conversor-cm-para-polegada': typeof ConversorCmParaPolegadaRoute
  '/conversor-litros-para-m3': typeof ConversorLitrosParaM3Route
  '/conversor-m2-para-hectare': typeof ConversorM2ParaHectareRoute
  '/conversores': typeof ConversoresRoute
  '/economia-energia-solar': typeof EconomiaEnergiaSolarRoute
  '/energia-solar': typeof EnergiaSolarRouteWithChildren
  '/equipe': typeof EquipeRoute
  '/faq': typeof FaqRoute
  '/metodologia': typeof MetodologiaRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-dmca': typeof PoliticaDmcaRoute
  '/quantas-placas-solares-preciso': typeof QuantasPlacasSolaresPrecisoRoute
  '/simulador-solar-avancado': typeof SimuladorSolarAvancadoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/construcao-civil/andaimes-escoras': typeof ConstrucaoCivilAndaimesEscorasRoute
  '/construcao-civil/calculadora-lajes': typeof ConstrucaoCivilCalculadoraLajesRoute
  '/construcao-civil/calculadora-mao-obra': typeof ConstrucaoCivilCalculadoraMaoObraRoute
  '/construcao-civil/conversor-unidades-tecnicas': typeof ConstrucaoCivilConversorUnidadesTecnicasRoute
  '/construcao-civil/dimensionamento-eletrico': typeof ConstrucaoCivilDimensionamentoEletricoRoute
  '/construcao-civil/drenagem-calhas': typeof ConstrucaoCivilDrenagemCalhasRoute
  '/construcao-civil/estruturas-metalicas-basicas': typeof ConstrucaoCivilEstruturasMetalicasBasicasRoute
  '/construcao-civil/fundacao-sapata': typeof ConstrucaoCivilFundacaoSapataRoute
  '/construcao-civil/hvac-perdas': typeof ConstrucaoCivilHvacPerdasRoute
  '/construcao-civil/orcamento-por-etapa': typeof ConstrucaoCivilOrcamentoPorEtapaRoute
  '/construcao-civil/perda-atrito-tubulacoes': typeof ConstrucaoCivilPerdaAtritoTubulacoesRoute
  '/construcao-civil/quantificacao-telhas-pecas': typeof ConstrucaoCivilQuantificacaoTelhasPecasRoute
  '/construcao-civil/simulador-iluminacao-fachadas': typeof ConstrucaoCivilSimuladorIluminacaoFachadasRoute
  '/energia-solar/calculadora-area-layout-paineis': typeof EnergiaSolarCalculadoraAreaLayoutPaineisRoute
  '/energia-solar/calculadora-bateria': typeof EnergiaSolarCalculadoraBateriaRoute
  '/energia-solar/calculadora-inversor': typeof EnergiaSolarCalculadoraInversorRoute
  '/energia-solar/calculadora-payback': typeof EnergiaSolarCalculadoraPaybackRoute
  '/energia-solar/calculadora-perdas-eficiencia': typeof EnergiaSolarCalculadoraPerdasEficienciaRoute
  '/energia-solar/comparador-sistemas': typeof EnergiaSolarComparadorSistemasRoute
  '/energia-solar/conversor-kw-kwh': typeof EnergiaSolarConversorKwKwhRoute
  '/energia-solar/estimador-custo-total': typeof EnergiaSolarEstimadorCustoTotalRoute
  '/energia-solar/incentivos-subsidios-regionais': typeof EnergiaSolarIncentivosSubsidiosRegionaisRoute
  '/energia-solar/simulacao-radiacao': typeof EnergiaSolarSimulacaoRadiacaoRoute
  '/ferramentas/orcamento-domestico': typeof FerramentasOrcamentoDomesticoRoute
  '/construcao-civil/': typeof ConstrucaoCivilIndexRoute
  '/energia-solar/': typeof EnergiaSolarIndexRoute
  '/blog/categoria/$categoria': typeof BlogCategoriaCategoriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-legal'
    | '/blog'
    | '/calculadora-ar-condicionado'
    | '/calculadora-de-aco'
    | '/calculadora-de-areia'
    | '/calculadora-de-argamassa'
    | '/calculadora-de-blocos'
    | '/calculadora-de-brita'
    | '/calculadora-de-cimento'
    | '/calculadora-de-concreto'
    | '/calculadora-de-esquadrias'
    | '/calculadora-de-forma'
    | '/calculadora-de-piso'
    | '/calculadora-de-reboco'
    | '/calculadora-de-telhas'
    | '/calculadora-de-tijolos'
    | '/calculadora-de-tinta'
    | '/calculadora-de-tubos'
    | '/calculadora-rejunte'
    | '/construcao-civil'
    | '/contato'
    | '/conversor-cm-para-polegada'
    | '/conversor-litros-para-m3'
    | '/conversor-m2-para-hectare'
    | '/conversores'
    | '/economia-energia-solar'
    | '/energia-solar'
    | '/equipe'
    | '/faq'
    | '/metodologia'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/politica-dmca'
    | '/quantas-placas-solares-preciso'
    | '/simulador-solar-avancado'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos-de-uso'
    | '/blog/$slug'
    | '/construcao-civil/andaimes-escoras'
    | '/construcao-civil/calculadora-lajes'
    | '/construcao-civil/calculadora-mao-obra'
    | '/construcao-civil/conversor-unidades-tecnicas'
    | '/construcao-civil/dimensionamento-eletrico'
    | '/construcao-civil/drenagem-calhas'
    | '/construcao-civil/estruturas-metalicas-basicas'
    | '/construcao-civil/fundacao-sapata'
    | '/construcao-civil/hvac-perdas'
    | '/construcao-civil/orcamento-por-etapa'
    | '/construcao-civil/perda-atrito-tubulacoes'
    | '/construcao-civil/quantificacao-telhas-pecas'
    | '/construcao-civil/simulador-iluminacao-fachadas'
    | '/energia-solar/calculadora-area-layout-paineis'
    | '/energia-solar/calculadora-bateria'
    | '/energia-solar/calculadora-inversor'
    | '/energia-solar/calculadora-payback'
    | '/energia-solar/calculadora-perdas-eficiencia'
    | '/energia-solar/comparador-sistemas'
    | '/energia-solar/conversor-kw-kwh'
    | '/energia-solar/estimador-custo-total'
    | '/energia-solar/incentivos-subsidios-regionais'
    | '/energia-solar/simulacao-radiacao'
    | '/ferramentas/orcamento-domestico'
    | '/construcao-civil/'
    | '/energia-solar/'
    | '/blog/categoria/$categoria'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-legal'
    | '/blog'
    | '/calculadora-ar-condicionado'
    | '/calculadora-de-aco'
    | '/calculadora-de-areia'
    | '/calculadora-de-argamassa'
    | '/calculadora-de-blocos'
    | '/calculadora-de-brita'
    | '/calculadora-de-cimento'
    | '/calculadora-de-concreto'
    | '/calculadora-de-esquadrias'
    | '/calculadora-de-forma'
    | '/calculadora-de-piso'
    | '/calculadora-de-reboco'
    | '/calculadora-de-telhas'
    | '/calculadora-de-tijolos'
    | '/calculadora-de-tinta'
    | '/calculadora-de-tubos'
    | '/calculadora-rejunte'
    | '/contato'
    | '/conversor-cm-para-polegada'
    | '/conversor-litros-para-m3'
    | '/conversor-m2-para-hectare'
    | '/conversores'
    | '/economia-energia-solar'
    | '/equipe'
    | '/faq'
    | '/metodologia'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/politica-dmca'
    | '/quantas-placas-solares-preciso'
    | '/simulador-solar-avancado'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos-de-uso'
    | '/blog/$slug'
    | '/construcao-civil/andaimes-escoras'
    | '/construcao-civil/calculadora-lajes'
    | '/construcao-civil/calculadora-mao-obra'
    | '/construcao-civil/conversor-unidades-tecnicas'
    | '/construcao-civil/dimensionamento-eletrico'
    | '/construcao-civil/drenagem-calhas'
    | '/construcao-civil/estruturas-metalicas-basicas'
    | '/construcao-civil/fundacao-sapata'
    | '/construcao-civil/hvac-perdas'
    | '/construcao-civil/orcamento-por-etapa'
    | '/construcao-civil/perda-atrito-tubulacoes'
    | '/construcao-civil/quantificacao-telhas-pecas'
    | '/construcao-civil/simulador-iluminacao-fachadas'
    | '/energia-solar/calculadora-area-layout-paineis'
    | '/energia-solar/calculadora-bateria'
    | '/energia-solar/calculadora-inversor'
    | '/energia-solar/calculadora-payback'
    | '/energia-solar/calculadora-perdas-eficiencia'
    | '/energia-solar/comparador-sistemas'
    | '/energia-solar/conversor-kw-kwh'
    | '/energia-solar/estimador-custo-total'
    | '/energia-solar/incentivos-subsidios-regionais'
    | '/energia-solar/simulacao-radiacao'
    | '/ferramentas/orcamento-domestico'
    | '/construcao-civil'
    | '/energia-solar'
    | '/blog/categoria/$categoria'
  id:
    | '__root__'
    | '/'
    | '/aviso-legal'
    | '/blog'
    | '/calculadora-ar-condicionado'
    | '/calculadora-de-aco'
    | '/calculadora-de-areia'
    | '/calculadora-de-argamassa'
    | '/calculadora-de-blocos'
    | '/calculadora-de-brita'
    | '/calculadora-de-cimento'
    | '/calculadora-de-concreto'
    | '/calculadora-de-esquadrias'
    | '/calculadora-de-forma'
    | '/calculadora-de-piso'
    | '/calculadora-de-reboco'
    | '/calculadora-de-telhas'
    | '/calculadora-de-tijolos'
    | '/calculadora-de-tinta'
    | '/calculadora-de-tubos'
    | '/calculadora-rejunte'
    | '/construcao-civil'
    | '/contato'
    | '/conversor-cm-para-polegada'
    | '/conversor-litros-para-m3'
    | '/conversor-m2-para-hectare'
    | '/conversores'
    | '/economia-energia-solar'
    | '/energia-solar'
    | '/equipe'
    | '/faq'
    | '/metodologia'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/politica-dmca'
    | '/quantas-placas-solares-preciso'
    | '/simulador-solar-avancado'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos-de-uso'
    | '/blog/$slug'
    | '/construcao-civil/andaimes-escoras'
    | '/construcao-civil/calculadora-lajes'
    | '/construcao-civil/calculadora-mao-obra'
    | '/construcao-civil/conversor-unidades-tecnicas'
    | '/construcao-civil/dimensionamento-eletrico'
    | '/construcao-civil/drenagem-calhas'
    | '/construcao-civil/estruturas-metalicas-basicas'
    | '/construcao-civil/fundacao-sapata'
    | '/construcao-civil/hvac-perdas'
    | '/construcao-civil/orcamento-por-etapa'
    | '/construcao-civil/perda-atrito-tubulacoes'
    | '/construcao-civil/quantificacao-telhas-pecas'
    | '/construcao-civil/simulador-iluminacao-fachadas'
    | '/energia-solar/calculadora-area-layout-paineis'
    | '/energia-solar/calculadora-bateria'
    | '/energia-solar/calculadora-inversor'
    | '/energia-solar/calculadora-payback'
    | '/energia-solar/calculadora-perdas-eficiencia'
    | '/energia-solar/comparador-sistemas'
    | '/energia-solar/conversor-kw-kwh'
    | '/energia-solar/estimador-custo-total'
    | '/energia-solar/incentivos-subsidios-regionais'
    | '/energia-solar/simulacao-radiacao'
    | '/ferramentas/orcamento-domestico'
    | '/construcao-civil/'
    | '/energia-solar/'
    | '/blog/categoria/$categoria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  BlogRoute: typeof BlogRouteWithChildren
  CalculadoraArCondicionadoRoute: typeof CalculadoraArCondicionadoRoute
  CalculadoraDeAcoRoute: typeof CalculadoraDeAcoRoute
  CalculadoraDeAreiaRoute: typeof CalculadoraDeAreiaRoute
  CalculadoraDeArgamassaRoute: typeof CalculadoraDeArgamassaRoute
  CalculadoraDeBlocosRoute: typeof CalculadoraDeBlocosRoute
  CalculadoraDeBritaRoute: typeof CalculadoraDeBritaRoute
  CalculadoraDeCimentoRoute: typeof CalculadoraDeCimentoRoute
  CalculadoraDeConcretoRoute: typeof CalculadoraDeConcretoRoute
  CalculadoraDeEsquadriasRoute: typeof CalculadoraDeEsquadriasRoute
  CalculadoraDeFormaRoute: typeof CalculadoraDeFormaRoute
  CalculadoraDePisoRoute: typeof CalculadoraDePisoRoute
  CalculadoraDeRebocoRoute: typeof CalculadoraDeRebocoRoute
  CalculadoraDeTelhasRoute: typeof CalculadoraDeTelhasRoute
  CalculadoraDeTijolosRoute: typeof CalculadoraDeTijolosRoute
  CalculadoraDeTintaRoute: typeof CalculadoraDeTintaRoute
  CalculadoraDeTubosRoute: typeof CalculadoraDeTubosRoute
  CalculadoraRejunteRoute: typeof CalculadoraRejunteRoute
  ConstrucaoCivilRoute: typeof ConstrucaoCivilRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  ConversorCmParaPolegadaRoute: typeof ConversorCmParaPolegadaRoute
  ConversorLitrosParaM3Route: typeof ConversorLitrosParaM3Route
  ConversorM2ParaHectareRoute: typeof ConversorM2ParaHectareRoute
  ConversoresRoute: typeof ConversoresRoute
  EconomiaEnergiaSolarRoute: typeof EconomiaEnergiaSolarRoute
  EnergiaSolarRoute: typeof EnergiaSolarRouteWithChildren
  EquipeRoute: typeof EquipeRoute
  FaqRoute: typeof FaqRoute
  MetodologiaRoute: typeof MetodologiaRoute
  PoliticaDeCookiesRoute: typeof PoliticaDeCookiesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  PoliticaDmcaRoute: typeof PoliticaDmcaRoute
  QuantasPlacasSolaresPrecisoRoute: typeof QuantasPlacasSolaresPrecisoRoute
  SimuladorSolarAvancadoRoute: typeof SimuladorSolarAvancadoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  FerramentasOrcamentoDomesticoRoute: typeof FerramentasOrcamentoDomesticoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulador-solar-avancado': {
      id: '/simulador-solar-avancado'
      path: '/simulador-solar-avancado'
      fullPath: '/simulador-solar-avancado'
      preLoaderRoute: typeof SimuladorSolarAvancadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quantas-placas-solares-preciso': {
      id: '/quantas-placas-solares-preciso'
      path: '/quantas-placas-solares-preciso'
      fullPath: '/quantas-placas-solares-preciso'
      preLoaderRoute: typeof QuantasPlacasSolaresPrecisoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-dmca': {
      id: '/politica-dmca'
      path: '/politica-dmca'
      fullPath: '/politica-dmca'
      preLoaderRoute: typeof PoliticaDmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-cookies': {
      id: '/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PoliticaDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia-solar': {
      id: '/energia-solar'
      path: '/energia-solar'
      fullPath: '/energia-solar'
      preLoaderRoute: typeof EnergiaSolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economia-energia-solar': {
      id: '/economia-energia-solar'
      path: '/economia-energia-solar'
      fullPath: '/economia-energia-solar'
      preLoaderRoute: typeof EconomiaEnergiaSolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversores': {
      id: '/conversores'
      path: '/conversores'
      fullPath: '/conversores'
      preLoaderRoute: typeof ConversoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversor-m2-para-hectare': {
      id: '/conversor-m2-para-hectare'
      path: '/conversor-m2-para-hectare'
      fullPath: '/conversor-m2-para-hectare'
      preLoaderRoute: typeof ConversorM2ParaHectareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversor-litros-para-m3': {
      id: '/conversor-litros-para-m3'
      path: '/conversor-litros-para-m3'
      fullPath: '/conversor-litros-para-m3'
      preLoaderRoute: typeof ConversorLitrosParaM3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversor-cm-para-polegada': {
      id: '/conversor-cm-para-polegada'
      path: '/conversor-cm-para-polegada'
      fullPath: '/conversor-cm-para-polegada'
      preLoaderRoute: typeof ConversorCmParaPolegadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construcao-civil': {
      id: '/construcao-civil'
      path: '/construcao-civil'
      fullPath: '/construcao-civil'
      preLoaderRoute: typeof ConstrucaoCivilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-rejunte': {
      id: '/calculadora-rejunte'
      path: '/calculadora-rejunte'
      fullPath: '/calculadora-rejunte'
      preLoaderRoute: typeof CalculadoraRejunteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-de-tubos': {
      id: '/calculadora-de-tubos'
      path: '/calculadora-de-tubos'
      fullPath: '/calculadora-de-tubos'
      preLoaderRoute: typeof CalculadoraDeTubosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-de-tinta': {
      id: '/calculadora-de-tinta'
      path: '/calculadora-de-tinta'
      fullPath: '/calculadora-de-tinta'
      preLoaderRoute: typeof CalculadoraDeTintaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-de-tijolos': {
      id: '/calculadora-de-tijolos'
      path: '/calculadora-de-tijolos'
      fullPath: '/calculadora-de-tijolos'
      preLoaderRoute: typeof CalculadoraDeTijolosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-de-telhas': {
      id: '/calculadora-de-telhas'
      path: '/calculadora-de-telhas'
      fullPath: '/calculadora-de-telhas'
      preLoaderRoute: typeof CalculadoraDeTelhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-de-reboco': {
      id: '/calculadora-de-reboco'
      path: '/calculadora-de-reboco'
      fullPath: '/calculadora-de-reboco'
      preLoaderRoute: typeof CalculadoraDeRebocoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-de-piso': {
      id: '/calculadora-de-piso'
      path: '/calculadora-de-piso'
      fullPath: '/calculadora-de-piso'
      preLoaderRoute: typeof CalculadoraDePisoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-de-forma': {
      id: '/calculadora-de-forma'
      path: '/calculadora-de-forma'
      fullPath: '/calculadora-de-forma'
      preLoaderRoute: typeof CalculadoraDeFormaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-de-esquadrias': {
      id: '/calculadora-de-esquadrias'
      path: '/calculadora-de-esquadrias'
      fullPath: '/calculadora-de-esquadrias'
      preLoaderRoute: typeof CalculadoraDeEsquadriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-de-concreto': {
      id: '/calculadora-de-concreto'
      path: '/calculadora-de-concreto'
      fullPath: '/calculadora-de-concreto'
      preLoaderRoute: typeof CalculadoraDeConcretoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-de-cimento': {
      id: '/calculadora-de-cimento'
      path: '/calculadora-de-cimento'
      fullPath: '/calculadora-de-cimento'
      preLoaderRoute: typeof CalculadoraDeCimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-de-brita': {
      id: '/calculadora-de-brita'
      path: '/calculadora-de-brita'
      fullPath: '/calculadora-de-brita'
      preLoaderRoute: typeof CalculadoraDeBritaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-de-blocos': {
      id: '/calculadora-de-blocos'
      path: '/calculadora-de-blocos'
      fullPath: '/calculadora-de-blocos'
      preLoaderRoute: typeof CalculadoraDeBlocosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-de-argamassa': {
      id: '/calculadora-de-argamassa'
      path: '/calculadora-de-argamassa'
      fullPath: '/calculadora-de-argamassa'
      preLoaderRoute: typeof CalculadoraDeArgamassaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-de-areia': {
      id: '/calculadora-de-areia'
      path: '/calculadora-de-areia'
      fullPath: '/calculadora-de-areia'
      preLoaderRoute: typeof CalculadoraDeAreiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-de-aco': {
      id: '/calculadora-de-aco'
      path: '/calculadora-de-aco'
      fullPath: '/calculadora-de-aco'
      preLoaderRoute: typeof CalculadoraDeAcoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-ar-condicionado': {
      id: '/calculadora-ar-condicionado'
      path: '/calculadora-ar-condicionado'
      fullPath: '/calculadora-ar-condicionado'
      preLoaderRoute: typeof CalculadoraArCondicionadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia-solar/': {
      id: '/energia-solar/'
      path: '/'
      fullPath: '/energia-solar/'
      preLoaderRoute: typeof EnergiaSolarIndexRouteImport
      parentRoute: typeof EnergiaSolarRoute
    }
    '/construcao-civil/': {
      id: '/construcao-civil/'
      path: '/'
      fullPath: '/construcao-civil/'
      preLoaderRoute: typeof ConstrucaoCivilIndexRouteImport
      parentRoute: typeof ConstrucaoCivilRoute
    }
    '/ferramentas/orcamento-domestico': {
      id: '/ferramentas/orcamento-domestico'
      path: '/ferramentas/orcamento-domestico'
      fullPath: '/ferramentas/orcamento-domestico'
      preLoaderRoute: typeof FerramentasOrcamentoDomesticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia-solar/simulacao-radiacao': {
      id: '/energia-solar/simulacao-radiacao'
      path: '/simulacao-radiacao'
      fullPath: '/energia-solar/simulacao-radiacao'
      preLoaderRoute: typeof EnergiaSolarSimulacaoRadiacaoRouteImport
      parentRoute: typeof EnergiaSolarRoute
    }
    '/energia-solar/incentivos-subsidios-regionais': {
      id: '/energia-solar/incentivos-subsidios-regionais'
      path: '/incentivos-subsidios-regionais'
      fullPath: '/energia-solar/incentivos-subsidios-regionais'
      preLoaderRoute: typeof EnergiaSolarIncentivosSubsidiosRegionaisRouteImport
      parentRoute: typeof EnergiaSolarRoute
    }
    '/energia-solar/estimador-custo-total': {
      id: '/energia-solar/estimador-custo-total'
      path: '/estimador-custo-total'
      fullPath: '/energia-solar/estimador-custo-total'
      preLoaderRoute: typeof EnergiaSolarEstimadorCustoTotalRouteImport
      parentRoute: typeof EnergiaSolarRoute
    }
    '/energia-solar/conversor-kw-kwh': {
      id: '/energia-solar/conversor-kw-kwh'
      path: '/conversor-kw-kwh'
      fullPath: '/energia-solar/conversor-kw-kwh'
      preLoaderRoute: typeof EnergiaSolarConversorKwKwhRouteImport
      parentRoute: typeof EnergiaSolarRoute
    }
    '/energia-solar/comparador-sistemas': {
      id: '/energia-solar/comparador-sistemas'
      path: '/comparador-sistemas'
      fullPath: '/energia-solar/comparador-sistemas'
      preLoaderRoute: typeof EnergiaSolarComparadorSistemasRouteImport
      parentRoute: typeof EnergiaSolarRoute
    }
    '/energia-solar/calculadora-perdas-eficiencia': {
      id: '/energia-solar/calculadora-perdas-eficiencia'
      path: '/calculadora-perdas-eficiencia'
      fullPath: '/energia-solar/calculadora-perdas-eficiencia'
      preLoaderRoute: typeof EnergiaSolarCalculadoraPerdasEficienciaRouteImport
      parentRoute: typeof EnergiaSolarRoute
    }
    '/energia-solar/calculadora-payback': {
      id: '/energia-solar/calculadora-payback'
      path: '/calculadora-payback'
      fullPath: '/energia-solar/calculadora-payback'
      preLoaderRoute: typeof EnergiaSolarCalculadoraPaybackRouteImport
      parentRoute: typeof EnergiaSolarRoute
    }
    '/energia-solar/calculadora-inversor': {
      id: '/energia-solar/calculadora-inversor'
      path: '/calculadora-inversor'
      fullPath: '/energia-solar/calculadora-inversor'
      preLoaderRoute: typeof EnergiaSolarCalculadoraInversorRouteImport
      parentRoute: typeof EnergiaSolarRoute
    }
    '/energia-solar/calculadora-bateria': {
      id: '/energia-solar/calculadora-bateria'
      path: '/calculadora-bateria'
      fullPath: '/energia-solar/calculadora-bateria'
      preLoaderRoute: typeof EnergiaSolarCalculadoraBateriaRouteImport
      parentRoute: typeof EnergiaSolarRoute
    }
    '/energia-solar/calculadora-area-layout-paineis': {
      id: '/energia-solar/calculadora-area-layout-paineis'
      path: '/calculadora-area-layout-paineis'
      fullPath: '/energia-solar/calculadora-area-layout-paineis'
      preLoaderRoute: typeof EnergiaSolarCalculadoraAreaLayoutPaineisRouteImport
      parentRoute: typeof EnergiaSolarRoute
    }
    '/construcao-civil/simulador-iluminacao-fachadas': {
      id: '/construcao-civil/simulador-iluminacao-fachadas'
      path: '/simulador-iluminacao-fachadas'
      fullPath: '/construcao-civil/simulador-iluminacao-fachadas'
      preLoaderRoute: typeof ConstrucaoCivilSimuladorIluminacaoFachadasRouteImport
      parentRoute: typeof ConstrucaoCivilRoute
    }
    '/construcao-civil/quantificacao-telhas-pecas': {
      id: '/construcao-civil/quantificacao-telhas-pecas'
      path: '/quantificacao-telhas-pecas'
      fullPath: '/construcao-civil/quantificacao-telhas-pecas'
      preLoaderRoute: typeof ConstrucaoCivilQuantificacaoTelhasPecasRouteImport
      parentRoute: typeof ConstrucaoCivilRoute
    }
    '/construcao-civil/perda-atrito-tubulacoes': {
      id: '/construcao-civil/perda-atrito-tubulacoes'
      path: '/perda-atrito-tubulacoes'
      fullPath: '/construcao-civil/perda-atrito-tubulacoes'
      preLoaderRoute: typeof ConstrucaoCivilPerdaAtritoTubulacoesRouteImport
      parentRoute: typeof ConstrucaoCivilRoute
    }
    '/construcao-civil/orcamento-por-etapa': {
      id: '/construcao-civil/orcamento-por-etapa'
      path: '/orcamento-por-etapa'
      fullPath: '/construcao-civil/orcamento-por-etapa'
      preLoaderRoute: typeof ConstrucaoCivilOrcamentoPorEtapaRouteImport
      parentRoute: typeof ConstrucaoCivilRoute
    }
    '/construcao-civil/hvac-perdas': {
      id: '/construcao-civil/hvac-perdas'
      path: '/hvac-perdas'
      fullPath: '/construcao-civil/hvac-perdas'
      preLoaderRoute: typeof ConstrucaoCivilHvacPerdasRouteImport
      parentRoute: typeof ConstrucaoCivilRoute
    }
    '/construcao-civil/fundacao-sapata': {
      id: '/construcao-civil/fundacao-sapata'
      path: '/fundacao-sapata'
      fullPath: '/construcao-civil/fundacao-sapata'
      preLoaderRoute: typeof ConstrucaoCivilFundacaoSapataRouteImport
      parentRoute: typeof ConstrucaoCivilRoute
    }
    '/construcao-civil/estruturas-metalicas-basicas': {
      id: '/construcao-civil/estruturas-metalicas-basicas'
      path: '/estruturas-metalicas-basicas'
      fullPath: '/construcao-civil/estruturas-metalicas-basicas'
      preLoaderRoute: typeof ConstrucaoCivilEstruturasMetalicasBasicasRouteImport
      parentRoute: typeof ConstrucaoCivilRoute
    }
    '/construcao-civil/drenagem-calhas': {
      id: '/construcao-civil/drenagem-calhas'
      path: '/drenagem-calhas'
      fullPath: '/construcao-civil/drenagem-calhas'
      preLoaderRoute: typeof ConstrucaoCivilDrenagemCalhasRouteImport
      parentRoute: typeof ConstrucaoCivilRoute
    }
    '/construcao-civil/dimensionamento-eletrico': {
      id: '/construcao-civil/dimensionamento-eletrico'
      path: '/dimensionamento-eletrico'
      fullPath: '/construcao-civil/dimensionamento-eletrico'
      preLoaderRoute: typeof ConstrucaoCivilDimensionamentoEletricoRouteImport
      parentRoute: typeof ConstrucaoCivilRoute
    }
    '/construcao-civil/conversor-unidades-tecnicas': {
      id: '/construcao-civil/conversor-unidades-tecnicas'
      path: '/conversor-unidades-tecnicas'
      fullPath: '/construcao-civil/conversor-unidades-tecnicas'
      preLoaderRoute: typeof ConstrucaoCivilConversorUnidadesTecnicasRouteImport
      parentRoute: typeof ConstrucaoCivilRoute
    }
    '/construcao-civil/calculadora-mao-obra': {
      id: '/construcao-civil/calculadora-mao-obra'
      path: '/calculadora-mao-obra'
      fullPath: '/construcao-civil/calculadora-mao-obra'
      preLoaderRoute: typeof ConstrucaoCivilCalculadoraMaoObraRouteImport
      parentRoute: typeof ConstrucaoCivilRoute
    }
    '/construcao-civil/calculadora-lajes': {
      id: '/construcao-civil/calculadora-lajes'
      path: '/calculadora-lajes'
      fullPath: '/construcao-civil/calculadora-lajes'
      preLoaderRoute: typeof ConstrucaoCivilCalculadoraLajesRouteImport
      parentRoute: typeof ConstrucaoCivilRoute
    }
    '/construcao-civil/andaimes-escoras': {
      id: '/construcao-civil/andaimes-escoras'
      path: '/andaimes-escoras'
      fullPath: '/construcao-civil/andaimes-escoras'
      preLoaderRoute: typeof ConstrucaoCivilAndaimesEscorasRouteImport
      parentRoute: typeof ConstrucaoCivilRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/categoria/$categoria': {
      id: '/blog/categoria/$categoria'
      path: '/categoria/$categoria'
      fullPath: '/blog/categoria/$categoria'
      preLoaderRoute: typeof BlogCategoriaCategoriaRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogCategoriaCategoriaRoute: typeof BlogCategoriaCategoriaRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogCategoriaCategoriaRoute: BlogCategoriaCategoriaRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ConstrucaoCivilRouteChildren {
  ConstrucaoCivilAndaimesEscorasRoute: typeof ConstrucaoCivilAndaimesEscorasRoute
  ConstrucaoCivilCalculadoraLajesRoute: typeof ConstrucaoCivilCalculadoraLajesRoute
  ConstrucaoCivilCalculadoraMaoObraRoute: typeof ConstrucaoCivilCalculadoraMaoObraRoute
  ConstrucaoCivilConversorUnidadesTecnicasRoute: typeof ConstrucaoCivilConversorUnidadesTecnicasRoute
  ConstrucaoCivilDimensionamentoEletricoRoute: typeof ConstrucaoCivilDimensionamentoEletricoRoute
  ConstrucaoCivilDrenagemCalhasRoute: typeof ConstrucaoCivilDrenagemCalhasRoute
  ConstrucaoCivilEstruturasMetalicasBasicasRoute: typeof ConstrucaoCivilEstruturasMetalicasBasicasRoute
  ConstrucaoCivilFundacaoSapataRoute: typeof ConstrucaoCivilFundacaoSapataRoute
  ConstrucaoCivilHvacPerdasRoute: typeof ConstrucaoCivilHvacPerdasRoute
  ConstrucaoCivilOrcamentoPorEtapaRoute: typeof ConstrucaoCivilOrcamentoPorEtapaRoute
  ConstrucaoCivilPerdaAtritoTubulacoesRoute: typeof ConstrucaoCivilPerdaAtritoTubulacoesRoute
  ConstrucaoCivilQuantificacaoTelhasPecasRoute: typeof ConstrucaoCivilQuantificacaoTelhasPecasRoute
  ConstrucaoCivilSimuladorIluminacaoFachadasRoute: typeof ConstrucaoCivilSimuladorIluminacaoFachadasRoute
  ConstrucaoCivilIndexRoute: typeof ConstrucaoCivilIndexRoute
}

const ConstrucaoCivilRouteChildren: ConstrucaoCivilRouteChildren = {
  ConstrucaoCivilAndaimesEscorasRoute: ConstrucaoCivilAndaimesEscorasRoute,
  ConstrucaoCivilCalculadoraLajesRoute: ConstrucaoCivilCalculadoraLajesRoute,
  ConstrucaoCivilCalculadoraMaoObraRoute:
    ConstrucaoCivilCalculadoraMaoObraRoute,
  ConstrucaoCivilConversorUnidadesTecnicasRoute:
    ConstrucaoCivilConversorUnidadesTecnicasRoute,
  ConstrucaoCivilDimensionamentoEletricoRoute:
    ConstrucaoCivilDimensionamentoEletricoRoute,
  ConstrucaoCivilDrenagemCalhasRoute: ConstrucaoCivilDrenagemCalhasRoute,
  ConstrucaoCivilEstruturasMetalicasBasicasRoute:
    ConstrucaoCivilEstruturasMetalicasBasicasRoute,
  ConstrucaoCivilFundacaoSapataRoute: ConstrucaoCivilFundacaoSapataRoute,
  ConstrucaoCivilHvacPerdasRoute: ConstrucaoCivilHvacPerdasRoute,
  ConstrucaoCivilOrcamentoPorEtapaRoute: ConstrucaoCivilOrcamentoPorEtapaRoute,
  ConstrucaoCivilPerdaAtritoTubulacoesRoute:
    ConstrucaoCivilPerdaAtritoTubulacoesRoute,
  ConstrucaoCivilQuantificacaoTelhasPecasRoute:
    ConstrucaoCivilQuantificacaoTelhasPecasRoute,
  ConstrucaoCivilSimuladorIluminacaoFachadasRoute:
    ConstrucaoCivilSimuladorIluminacaoFachadasRoute,
  ConstrucaoCivilIndexRoute: ConstrucaoCivilIndexRoute,
}

const ConstrucaoCivilRouteWithChildren = ConstrucaoCivilRoute._addFileChildren(
  ConstrucaoCivilRouteChildren,
)

interface EnergiaSolarRouteChildren {
  EnergiaSolarCalculadoraAreaLayoutPaineisRoute: typeof EnergiaSolarCalculadoraAreaLayoutPaineisRoute
  EnergiaSolarCalculadoraBateriaRoute: typeof EnergiaSolarCalculadoraBateriaRoute
  EnergiaSolarCalculadoraInversorRoute: typeof EnergiaSolarCalculadoraInversorRoute
  EnergiaSolarCalculadoraPaybackRoute: typeof EnergiaSolarCalculadoraPaybackRoute
  EnergiaSolarCalculadoraPerdasEficienciaRoute: typeof EnergiaSolarCalculadoraPerdasEficienciaRoute
  EnergiaSolarComparadorSistemasRoute: typeof EnergiaSolarComparadorSistemasRoute
  EnergiaSolarConversorKwKwhRoute: typeof EnergiaSolarConversorKwKwhRoute
  EnergiaSolarEstimadorCustoTotalRoute: typeof EnergiaSolarEstimadorCustoTotalRoute
  EnergiaSolarIncentivosSubsidiosRegionaisRoute: typeof EnergiaSolarIncentivosSubsidiosRegionaisRoute
  EnergiaSolarSimulacaoRadiacaoRoute: typeof EnergiaSolarSimulacaoRadiacaoRoute
  EnergiaSolarIndexRoute: typeof EnergiaSolarIndexRoute
}

const EnergiaSolarRouteChildren: EnergiaSolarRouteChildren = {
  EnergiaSolarCalculadoraAreaLayoutPaineisRoute:
    EnergiaSolarCalculadoraAreaLayoutPaineisRoute,
  EnergiaSolarCalculadoraBateriaRoute: EnergiaSolarCalculadoraBateriaRoute,
  EnergiaSolarCalculadoraInversorRoute: EnergiaSolarCalculadoraInversorRoute,
  EnergiaSolarCalculadoraPaybackRoute: EnergiaSolarCalculadoraPaybackRoute,
  EnergiaSolarCalculadoraPerdasEficienciaRoute:
    EnergiaSolarCalculadoraPerdasEficienciaRoute,
  EnergiaSolarComparadorSistemasRoute: EnergiaSolarComparadorSistemasRoute,
  EnergiaSolarConversorKwKwhRoute: EnergiaSolarConversorKwKwhRoute,
  EnergiaSolarEstimadorCustoTotalRoute: EnergiaSolarEstimadorCustoTotalRoute,
  EnergiaSolarIncentivosSubsidiosRegionaisRoute:
    EnergiaSolarIncentivosSubsidiosRegionaisRoute,
  EnergiaSolarSimulacaoRadiacaoRoute: EnergiaSolarSimulacaoRadiacaoRoute,
  EnergiaSolarIndexRoute: EnergiaSolarIndexRoute,
}

const EnergiaSolarRouteWithChildren = EnergiaSolarRoute._addFileChildren(
  EnergiaSolarRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  BlogRoute: BlogRouteWithChildren,
  CalculadoraArCondicionadoRoute: CalculadoraArCondicionadoRoute,
  CalculadoraDeAcoRoute: CalculadoraDeAcoRoute,
  CalculadoraDeAreiaRoute: CalculadoraDeAreiaRoute,
  CalculadoraDeArgamassaRoute: CalculadoraDeArgamassaRoute,
  CalculadoraDeBlocosRoute: CalculadoraDeBlocosRoute,
  CalculadoraDeBritaRoute: CalculadoraDeBritaRoute,
  CalculadoraDeCimentoRoute: CalculadoraDeCimentoRoute,
  CalculadoraDeConcretoRoute: CalculadoraDeConcretoRoute,
  CalculadoraDeEsquadriasRoute: CalculadoraDeEsquadriasRoute,
  CalculadoraDeFormaRoute: CalculadoraDeFormaRoute,
  CalculadoraDePisoRoute: CalculadoraDePisoRoute,
  CalculadoraDeRebocoRoute: CalculadoraDeRebocoRoute,
  CalculadoraDeTelhasRoute: CalculadoraDeTelhasRoute,
  CalculadoraDeTijolosRoute: CalculadoraDeTijolosRoute,
  CalculadoraDeTintaRoute: CalculadoraDeTintaRoute,
  CalculadoraDeTubosRoute: CalculadoraDeTubosRoute,
  CalculadoraRejunteRoute: CalculadoraRejunteRoute,
  ConstrucaoCivilRoute: ConstrucaoCivilRouteWithChildren,
  ContatoRoute: ContatoRoute,
  ConversorCmParaPolegadaRoute: ConversorCmParaPolegadaRoute,
  ConversorLitrosParaM3Route: ConversorLitrosParaM3Route,
  ConversorM2ParaHectareRoute: ConversorM2ParaHectareRoute,
  ConversoresRoute: ConversoresRoute,
  EconomiaEnergiaSolarRoute: EconomiaEnergiaSolarRoute,
  EnergiaSolarRoute: EnergiaSolarRouteWithChildren,
  EquipeRoute: EquipeRoute,
  FaqRoute: FaqRoute,
  MetodologiaRoute: MetodologiaRoute,
  PoliticaDeCookiesRoute: PoliticaDeCookiesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  PoliticaDmcaRoute: PoliticaDmcaRoute,
  QuantasPlacasSolaresPrecisoRoute: QuantasPlacasSolaresPrecisoRoute,
  SimuladorSolarAvancadoRoute: SimuladorSolarAvancadoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  FerramentasOrcamentoDomesticoRoute: FerramentasOrcamentoDomesticoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
